### ISSUE TITLE
前端 blank=true 验证错误

### ISSUE THREAD

**Issue by github3ape** [mtianyan/django-react-tyadmin#38]
我的字段是这样的：
nonce = models.PositiveIntegerField(verbose_name='Nonce', blank=True, null=True)
nonce 允许留空。

在前端编辑后，却提示我不能为空。
![图片](https://user-images.githubusercontent.com/101156743/164174605-deba60a9-82cf-4ed0-9d88-a16a84d01099.png)

**Comment by mtianyan** [comment]
@github3ape  这个是drf对于这个字段验证的问题.参考: https://stackoverflow.com/questions/49753316/django-rest-framework-a-valid-integer-is-required
